name: Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - run: mvn --batch-mode --update-snapshots verify
      - run: cp docs/uml.png target/site/apidocs
      - uses: montudor/action-zip@v1
      - working-directory: target
        run: zip site/apidocs/json-tools.zip json-tools*.jar
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: target/site/apidocs
      - uses: actions/deploy-pages@v2
