name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - run: mvn -q -B -U verify
      - run: cp docs/uml.png target/site/apidocs
      - uses: montudor/action-zip@v1
      - working-directory: target
        run: zip site/apidocs/json-tools.zip json-tools*.jar
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: target/site/apidocs
      - uses: actions/deploy-pages@v2
      - uses: actions/create-release@v1
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/site/apidocs/json-tools.zip
          asset_name: json-tools.zip
          asset_content_type: application/zip
